spring.application.name=backend
# CONFIGURACIÓN DEL SERVIDOR
server.port=8080

# CONFIGURACIÓN DE BASE DE DATOS POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_asistencia
spring.datasource.username=postgres
# AQUÍ VA LA CONTRASEÑA QUE CREASTE AL REINSTALAR POSTGRESQL
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CLAVE SECRETA PARA JWT (Debe ser larga y compleja en producción)
jwt.secret=TU_CLAVE_SECRETA_SUPER_SEGURA_DE_AL_MENOS_256_BITS_O_MAS
jwt.expiration=300000

# ===============================
# CONFIGURACIÓN DE CORREO (GMAIL)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true