spring.application.name=backend
# CONFIGURACIÓN DEL SERVIDOR
server.port=8080

# CONFIGURACIÓN DE BASE DE DATOS POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_asistencia
spring.datasource.username=postgres
# AQUÍ VA LA CONTRASEÑA QUE CREASTE AL REINSTALAR POSTGRESQL
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CLAVE SECRETA PARA JWT (Debe ser larga y compleja en producción)
jwt.secret=UnaClaveSuperSecretaParaFirmarLosTokensDelSistemaDeAsistencia2026
jwt.expiration=86400000